# Generated by Django 4.2.18 on 2025-03-28 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mysite", "0005_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="collections_allowed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
