# Generated by Django 4.2.18 on 2025-04-07 14:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0006_collection_creator_alter_collection_allowed_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemReview',
            new_name='Rating',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='stars',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('item', 'user')},
        ),
    ]
